---
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
library(magrittr)
```

# makeregions: Utility Tools to Create and Manipulate Genomic Regions

<!-- badges: start -->
<!-- badges: end -->

The package "makeregions" currently helps with the creation of genomic regions from GTF or BED files with options to filter specific features.

## Installation

You can install the development version of makeregions from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("tolgatabanli/metagene_windows")
```

## Example

```{r example}
library(makeregions)

example_file <- system.file("extdata", "data", "example.gtf", package = "makeregions")
result <- make_windows(input_file=example_file,
                       upstream = 1000, downstream = 2000,
                       feature = "gene", biotype = "lncRNA",
                       position = "start")$result
print(head(result))

```

